name: Code Health Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - development

jobs:
  health-check:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    name: Code Health Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Generate Jacoco
        if: always()
        run: ./mvnw jacoco:report

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Jacoco Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        if: always()
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_name: Coverage
          coverage_report_title: Jacoco
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 95
          fail_below_threshold: false
          publish_only_summary: false
